### ISSUE TITLE
Error for some .xlsx files

### ISSUE THREAD

**Issue by bazaglia** [Moblox/mongo-xlsx#10]
Although it works for some xlsx files, for other ones I get this error:

```
/Volumes/Data/Projects security/nxte/big-data/database/node_modules/mongo-xlsx/lib/mongo-xlsx.js:398
  mongoModel.forEach(function(f) {
             ^

TypeError: mongoModel.forEach is not a function
    at convertMongoModelToObject (/Volumes/Data/Projects security/nxte/big-data/database/node_modules/mongo-xlsx/lib/mongo-xlsx.js:398:14)
    at Object.exports.xlsxData2MongoData (/Volumes/Data/Projects security/nxte/big-data/database/node_modules/mongo-xlsx/lib/mongo-xlsx.js:328:24)
    at /Volumes/Data/Projects security/nxte/big-data/database/node_modules/mongo-xlsx/lib/mongo-xlsx.js:305:29
    at /Volumes/Data/Projects security/nxte/big-data/database/node_modules/mongo-xlsx/lib/xlsx-rw.js:69:12
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by bazaglia** [comment]
Fixed: it was due to multiple sheets in same file. I've had to split them into separate files.

**Comment by acedward** [comment]
If a single xlsx is parsed the result has the format [ { row1 } , { row2 } ]
if it has multiple pages the results has the format [[{ s1-row1 } , { s1-row2 }], [{ s2-row1 }, { s2-row2 }] ]

**Comment by bazaglia** [comment]
But `xlsx2MongoData` method fails when a file has multiple pages.

**Comment by acedward** [comment]
I just created a two-sheet excel file with one data-point per sheet.

```
const model = null;
const xlsx  = '/Users/eddie/Downloads/multipage-test.xlsx';
mongoxlsx.xlsx2MongoData(xlsx, model, (e, data) => console.log(data));
```

`[ [ { 'sheet-a-header-1': 'a' } ],  [ { 'sheet-b-header-1': 'b' } ] ]`

[multipage-test.xlsx](https://github.com/Moblox/mongo-xlsx/files/758412/multipage-test.xlsx)
