### ISSUE TITLE
not working with model mapping file

### ISSUE THREAD

**Issue by neha-gupta** [Moblox/mongo-xlsx#16]
The program works fine if model name passed as null. however, when I run it using mapping model it always lead to below error. Please help!

TypeError: mongoModel.forEach is not a function
    at convertMongoModelToObject (D:\react\react-redux\metrics-node-services\node_modules\mongo-xlsx\lib\mongo-xlsx.js:398:14)
    at Object.exports.xlsxData2MongoData (D:\react\react-redux\metrics-node-services\node_modules\mongo-xlsx\lib\mongo-xlsx.js:328:24)
    at D:\react\react-redux\metrics-node-services\node_modules\mongo-xlsx\lib\mongo-xlsx.js:294:26
    at D:\react\react-redux\metrics-node-services\node_modules\mongo-xlsx\lib\xlsx-rw.js:69:12
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
[model-config.txt](https://github.com/Moblox/mongo-xlsx/files/1599466/model-config.txt)
[sample-output-withNull.txt](https://github.com/Moblox/mongo-xlsx/files/1599467/sample-output-withNull.txt)

**Comment by neha-gupta** [comment]
This was issue with location mapper file. Hence closing
